settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.ngai216a9s.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: openshop-com-hk # unique identifier
    name: openshop.com.hk
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.openshop.com.hk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: i-openshop-com-hk
    name: i.openshop.com.hk
    description: 'Built for anything connected to the Internet.'
    url: 'https://i.openshop.com.hk'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: ERP-SYSTEM
    name: ERP SYSTEM
    url: 'https://172.105.127.190/jsf/login.faces'
    method: GET
    expectStatus: 200
    
  - id: WEBPOS
    name: WEBPOS
    url: 'https://webpos.openshop.com.hk'
    method: GET
    expectStatus: 200

  - id: 2000fun-com
    name: 2000fun.com
    url: 'https://www.2000fun.com/'
    method: GET
    expectStatus: 200
